spring:
  application:
    name: worker
  config:
    import: optional:configserver:http://localhost:8084/
  cloud:
    openfeign:
      circuitbreaker:
        enabled: true
eureka:
  instance:
    prefer-ip-address: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8085/eureka/


management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state.enabled: true
    liveness-state.enabled: true
  endpoint:
    health:
      probes:
        enabled: true
  metrics:
    tags:
      application: ${spring.application.name}


server:
  port: 8081


