spring:
  application:
    name: worker_microservice
  profiles:
    active: prod
  config:
    import: optional:configserver:http://localhost:8084/
  cloud:
    function:
      definition: execute
    stream:
      bindings:
        execute-in-0:
          destination: send-scenario
          group: ${spring.application.name}
        execute-out-0:
          destination: report-sent
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    connection-timeout: 10s
management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state.enabled: true
    liveness-state.enabled: true
  endpoint:
    health:
      probes:
        enabled: true
  metrics:
    tags:
      application: ${spring.application.name}

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8085/eureka/

server:
  port: 8081