version: '3.5'
services:
  flyway:
    image: flyway/flyway:9.22.1
    command: -configFiles=/flyway/conf/flyway.config -locations=filesystem:/flyway/sql -connectRetries=60 migrate
    volumes:
      - ${PWD}/tables:/flyway/sql
      - ${PWD}/flyway.config:/flyway/conf/flyway.config
    depends_on:
      - postgres
    networks:
      - db_network

  postgres:
    image: postgres:15.4
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=worker-logs
    networks:
      - db_network

networks:
  db_network:
    external:
      name: db_network
