name: Java CI with Gradle

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle
      - name: Set up ChromeDriver
        uses: nanasess/setup-chromedriver@v2
      - name: Move ChromeDriver to /opt
        run: |
          sudo mv /usr/local/bin/chromedriver /opt/chromedriver
          sudo chmod +x /opt/chromedriver
      - name: Set execute permissions for scripts
        run: |
          chmod +x flyway/migration/create.sh
          chmod +x flyway/migration/destroy.sh
      - name: Run Flyway migrations
        run: |
          cd flyway/migration
          docker network create db_network
          ./create.sh
          cd -
      - name: Install Gradle
        run: |
          wget https://services.gradle.org/distributions/gradle-7.3-bin.zip
          unzip -d /opt gradle-7.3-bin.zip
          export PATH=$PATH:/opt/gradle-7.3/bin
          gradle -v
      - name: Build and Run Tests
        run: |
          export DISPLAY=:99
          sudo Xvfb -ac :99 -screen 0 1280x1024x24 > /dev/null 2>&1 & # optional
          gradle test  # Use 'gradle' directly without './gradlew'
      - name: Publish Test Report
        if: ${{ always() }} # publish report even if the tests are failing
        uses: EnricoMi/publish-unit-test-result-action@v1
        with:
          directory: build/test-results/test
      - name: Stop and remove PostgreSQL Docker container
        run: |
          cd flyway/migration
          ./destroy.sh
          cd -
